trigger:
  - main
  
pool:
  vmImage: ubuntu-latest

stages:
- stage: DockerBuild
  jobs:
  - job: BuildImage
    steps:
    - task: Docker@2
      displayName: DockerBuild
      inputs:
        repository: 'nome_do_registry'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'